/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Website.glb 
*/
import React, { useState, useMemo, useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, PerspectiveCamera, Stars } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

function HoverableMesh({ geometry, material, position, rotation, scale, onClick }) {
  const [isHovered, setIsHovered] = useState(false);
  const mat = useMemo(() => (material ? material.clone() : null), [material]);

  useEffect(() => {
    if (!mat) return;
    if ("emissive" in mat) {
      const offEmissive = material?.emissive ?? 0x000000;
      const offIntensity = material?.emissiveIntensity ?? 0;
      mat.emissive.set(isHovered ? "orange" : offEmissive);
      mat.emissiveIntensity = isHovered ? 0.4 : offIntensity;
      mat.needsUpdate = true;
    }
  }, [isHovered, mat, material]);

  return (
    <mesh
      geometry={geometry}
      position={position}
      rotation={rotation}
      scale={scale}
      onClick={(e) => {
        e.stopPropagation();
        onClick?.(e);
      }}
      onPointerOver={(e) => {
        e.stopPropagation();
        setIsHovered(true);
        document.body.style.cursor = "pointer";
      }}
      onPointerOut={(e) => {
        e.stopPropagation();
        setIsHovered(false);
        document.body.style.cursor = "auto";
      }}
    >
      {mat && <primitive attach="material" object={mat} />}
    </mesh>
  );
}

export function Model(props) {
  const { scene } = useGLTF("/Website.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  return (
    <>
      <Stars radius={200} depth={50} count={15000} factor={15} fade speed={1} />
      <ambientLight intensity={0.6} color="#ffffff" />
      <group {...props} dispose={null}>
        <pointLight intensity={100} decay={2} color="#0046ff" position={[0, -2.773, -29.645]} />
        <spotLight intensity={500} angle={Math.PI / 4} penumbra={0.15} decay={2} color="#1cff00" position={[0, -7.74, 0]} rotation={[Math.PI / 2, 0, Math.PI]} target={nodes.Point001.target} >
          <primitive object={nodes.Point001.target} position={[0, 0, -1]} />
        </spotLight>
        <pointLight intensity={100} decay={2} color="#cf0800" position={[16.508, -2.75, 26.085]} />
        <PerspectiveCamera makeDefault={true} far={1000} near={0.1} fov={22.895} position={[-36.103, 53.767, 53.613]} rotation={[-0.825, -0.458, -0.446]}
        />
        <pointLight intensity={100} decay={2} color="#ff6a00" position={[-1.421, 3.65, -28.099]} />
        <pointLight intensity={100} decay={2} color="#ff4800" position={[-1.046, 3.77, -29.65]} />
        <mesh geometry={nodes.Chain.geometry} material={materials["Material.012"]} position={[0, 1, 2.35]} rotation={[0, 0, -Math.PI / 2]} />
        <group position={[-0.2, 2.8, -28.089]} rotation={[0.34, 1.101, -0.305]} scale={1.064}>
          <HoverableMesh geometry={nodes.Cube007.geometry} material={materials.Material} onClick={() => props.onSelectProject({ title: "Dreadnaught", imageSrc: "Dreadnaught.jpg", description: "Use a variety of tools to locate and track enemy ships.", skills: ["Unity 6", "C#"], demo: "https://matthewz80.itch.io/dreadnought", source: "https://matthewz80.itch.io/dreadnought", }) } />
          <mesh geometry={nodes.Cube007_1.geometry} material={materials["Material.013"]} />
          <mesh geometry={nodes.Cube007_2.geometry} material={materials["Material.003"]} />
          <mesh geometry={nodes.Cube007_3.geometry} material={materials["Material.017"]} />
        </group>
        {/* Anvil */}
        <group position={[0, 0, -1.494]}>
          <HoverableMesh geometry={nodes.Cone.geometry} material={materials["Material.004"]} onClick={() => props.onShowProjects?.()} />
          <mesh geometry={nodes.Cone_1.geometry} material={materials["Material.015"]} />
          <mesh geometry={nodes.Cone_2.geometry} material={materials["Material.014"]} />
          <mesh geometry={nodes.Cone_3.geometry} material={materials["Material.016"]} />
        </group>
        <mesh geometry={nodes.Chain001.geometry} material={materials["Material.012"]} position={[0.073, 1.18, 1.511]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Cone003.geometry} material={nodes.Cone003.material} position={[-2.714, 4.67, 0.245]} rotation={[0, -0.343, Math.PI]} scale={[14, 4, 14]} />
        <group position={[-2.714, 4.67, 0.245]} rotation={[0, -0.343, Math.PI]} scale={[14, 4, 14]}>
          <mesh geometry={nodes.Cone006.geometry} material={materials["Material.008"]} />
          <mesh geometry={nodes.Cone006_1.geometry} material={materials["Material.006"]} />
          <mesh geometry={nodes.Cone006_2.geometry} material={materials["Material.005"]} />
          <mesh geometry={nodes.Cone006_3.geometry} material={materials["Material.009"]} />
          {/* Linkedin */}
          <HoverableMesh geometry={nodes.Cone006_4.geometry} material={materials["Material.001"]} onClick={() => window.open("https://www.linkedin.com/in/stephen-tang-b8807325b/", "_blank") } />
        </group>
        <mesh geometry={nodes.Cone010.geometry} material={materials["Material.007"]} position={[-2.714, 4.67, 0.245]} rotation={[0, -0.343, Math.PI]} scale={[14, 4, 14]} />
        <group position={[-2.714, 4.67, 0.245]} rotation={[0, -0.343, Math.PI]} scale={[14, 4, 14]} >
          {/* Email */}
          <HoverableMesh geometry={nodes.Cone011.geometry} material={nodes.Cone011.material} onClick={() => { window.location.href = "mailto:sw2tang@uwaterloo.ca"; }} />
          <mesh geometry={nodes.Cone011_1.geometry} material={materials["Material.010"]} />
        </group>
        <group position={[-2.714, 4.67, 0.245]} rotation={[0, -0.343, Math.PI]} scale={[14, 4, 14]} >
          <HoverableMesh geometry={nodes.Cone012_1.geometry} material={nodes.Cone012_1.material}
            onClick={() => { const link = document.createElement("a");
              link.href = "/Resume.pdf";
              link.download = "Stephen Tang's Resume";
              document.body.appendChild(link);
              link.click();
              document.body.removeChild(link);
            }}
          />
          <mesh geometry={nodes.Cone012_2.geometry} material={materials["Material.011"]} />
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/Website.glb");
